blank_issues_enabled: true
contact_links:
  - name: The QA Company âœ‰ï¸
    url: https://the-qa-company.com/
    about: The QA Company web site
  - name: Support or questions ğŸ“š
    url: https://github.com/the-qa-company/qEndpoint/discussions
    about: Ask a question about QEndpoint
